apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/gbengard/e-signed-html.git
    targetRevision: HEAD
    path: /
    ksonnet: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
