version: 2.1
jobs:
  build-and-push-docker-image:
    machine: true
    docker:
      - image: cimg/python:3.8.4
    steps:
      - checkout
  
      # Authenticate with Docker Hub using environment variables
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

      # Build and tag the Docker image
      - run:
          name: Build and tag Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/my-app:latest .

      # Push the Docker image to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push $DOCKERHUB_USERNAME/my-app:latest
            

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-push-docker-image:
          context: credentials
