version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@3.1.0

workflows:
  the_jobs:
    jobs:
      - build-and-push-node1:
          context: Credentials

jobs:
  build-and-push-node1:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for V1
          command: |
            echo
            sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz 
            sudo tar -xvf node-v18.0.0-linux-x64.tar.xz 
            sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/ 
            node --version => v18.0.0
            sudo apt install nodejs
            docker build -t  gbengard/capstone:v1 .
            docker login -u gbengard -p $DOCKERHUB_TOKEN
            docker push gbengard/capstone:v1

