apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-eks-cluster
  region: us-east-1

availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d
  - us-east-1f

nodeGroups:
  - name: ng-1
    
    desiredCapacity: 1
    ssh:
      allow: true # Enable SSH access
      publicKeyName: EC2Tutorial
